books/urls.py
from django.urls import path
from .views import (
    CreateViewBook, 
    BooksListView, 
    DeleteBookView, 
    BookDetailView,
    BookUpdateView)

app_name = 'books'

urlpatterns = [
    path('', BooksListView.as_view(), name='list'),
    path('list/', BooksListView.as_view(), name='list'),
    path('create/', CreateViewBook.as_view(), name='create'),
    path('delete/<int:pk>/', DeleteBookView.as_view(), name='delete'),
    path('<int:pk>/', BookDetailView.as_view(), name='detail'),
    path('edit/<int:pk>/', BookUpdateView.as_view(), name='update'),
]

core/urls.py
from django.urls import path, include
from .views import IndexTemplateView, ContactFormView, ThankYouTemplateView, SingUpFormView
from django.contrib.auth import views as auth_views

app_name = 'core'

urlpatterns = [
    # path('',IndexTemplateView.as_view(), name='home'),
    # path('books/', include('books.urls'), name='books'),
    path('',include('books.urls'), name='home'),
    path('contact-us/', ContactFormView.as_view(), name='contact'),
    path('thank-you.html/', ThankYouTemplateView.as_view(), name='thank-you'),
    path('account/', include('django.contrib.auth.urls'), name='account'),
    path('account/login', auth_views.LoginView.as_view(extra_context={'nav_text_login':'active'}), name='login'),
    path('account/logout', auth_views.LogoutView.as_view(next_page='books:list'), name='logout'),
    path('account/singup', SingUpFormView.as_view(), name='singup'),
]

library/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('book/', include('books.urls')),
]

books/models.py
from django.db import models
from django.urls import reverse

class PublishingHouse(models.Model):
    name = models.CharField(max_length=50)
    address = models.TextField()

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class Book(models.Model):
    title = models.CharField(max_length=50)
    author = models.ManyToManyField(to=Author, related_name='author')
    publishing_year =models.DateField()
    publishing_house = models.ForeignKey(to=PublishingHouse, on_delete=models.PROTECT)
    pages = models.IntegerField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("books:detail", kwargs={"pk": self.pk})
    

core/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=50)
    email  = models.EmailField(max_length=254)
    phone = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self) -> str:
        return f'{self.name} -  {self.email}'

core/forms.py
from django import forms
from django.forms import fields
from django.forms.widgets import Textarea 
from .models import Contact
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField(max_length=25)
    message = forms.CharField(widget=Textarea)

    def load_in_db(self):
        # !Instancioamos el modelo
        contact = Contact()

        # !Cargamos los datos a cada campo
        contact.name = self.cleaned_data['name']
        contact.email = self.cleaned_data['email']
        contact.phone = self.cleaned_data['phone']
        contact.message = self.cleaned_data['message']

        # !Guardamos en base de datos 
        contact.save()

class SingUpForm(UserCreationForm):
    username = forms.CharField(max_length=30)

    class meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2',)

    # def authenticate_user(self, request):
    #     username = self.cleaned_data['username']
    #     password = self.cleaned_data['password1']
    #     user = authenticate(username=username, password=password)
    #     login(request, user)

books/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Book
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


# Create your views here.
class BooksListView(ListView):
    template_name = 'books/list.html'
    model = Book
    page_title = 'List Books'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_list'] = 'active'
        context['page_title'] = self.page_title
        context['count'] = Book.objects.count()
        return context

class BookDetailView(DetailView):
    template_name = 'books/detail.html'
    page_title = 'Book Detail'
    model = Book

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_detail'] = 'active'
        context['page_title'] = self.page_title
        return context

class DeleteBookView(PermissionRequiredMixin, DeleteView):
    permission_required = 'books.delete_book'
    template_name = 'books/delete.html'
    page_title = 'Delete Book'
    model = Book
    success_url = '/list/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_delete'] = 'active'
        context['page_title'] = self.page_title
        return context

class BookUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'books.change_book'
    template_name =  'books/create.html'
    page_title = 'Edit Book'
    model = Book
    fields = (
        'title',
        'author',
        'publishing_year',
        'publishing_house',
        'pages',
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_create'] = 'active'
        context['page_title'] = self.page_title
        context['book_pk'] = self.get_form().instance.id
        return context

class CreateViewBook(LoginRequiredMixin, CreateView):
    login_url = '/account/login'
    redirect_field_name = '/books/list/'

    template_name =  'books/create.html'
    page_title = 'Create Book'
    model = Book
    fields = (
        'title',
        'author',
        'publishing_year',
        'publishing_house',
        'pages',
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_create'] = 'active'
        context['page_title'] = self.page_title
        return context

core/views.py
from django.views.generic import TemplateView, FormView
from core.forms import ContactForm, SingUpForm

# Create your views here.
class IndexTemplateView(TemplateView):
    template_name = 'core/index.html'
    page_title = 'Index'

    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        return context

class ThankYouTemplateView(TemplateView):
    template_name = 'core/thank-you.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Thank-You'
        return context

class ContactFormView(FormView):
    template_name = 'core/contact-us.html'
    form_class = ContactForm
    success_url = '/thank-you.html/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Thank-You'
        context['nav_text_contact'] = 'active'
        return context

    def form_valid(self, form):
        form.load_in_db()
        return super().form_valid(form)

class SingUpFormView(FormView):
    template_name = 'core/singup.html'
    form_class = SingUpForm
    success_url = '/account/login'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nav_text_singup'] = 'active'
        return context

    def form_valid(self, form):
        form.save()
        # form.authenticate_user(self)
        return super().form_valid(form)

books/templates/books/create.html
{% extends 'core/main.html' %}
{% block main_content %}
    <style>

        h1 {
        color: white;
        font-weight: bold;
        text-align: center;
        margin: 1rem;
        margin-bottom: 4rem;
        }

        .div-form {
            border-radius: 10px;
            background-color: rgb(100, 98, 105);
        }

        .form-input {
            margin: 1rem;
        }

        .input-label {
            color: white;
            font-weight: bolder;
        }

    </style>

    <div class= "d-flex flex-column justify-content-center">

        <div>
        {% if book_pk %}
            <h1>Edit Book</h1>
        {% else %}
            <h1>New Book</h1>
        {% endif %}
        </div>

        <div class="d-flex justify-content-center m-3">
            <div class="div-form">

                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger m-2">
                        {{error}}
                        </div>
                    {% endfor %}
                {% endfor %}

                <form class="d-flex flex-column justify-content-between" method="POST" action="" style="width: 22rem;">
                    <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.title.label}}</div>{{form.title}}</div>
                    <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.author.label}}</div> {{form.author}}</div>
                    <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.publishing_year.label}}</div>{{form.publishing_year}}</div>
                    <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.publishing_house.label}}</div> {{form.publishing_house}}</div>
                    <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.pages.label}}</div>{{form.pages}}</div>
                    {% csrf_token %}


                    {% if book_pk %}
                    <button class="form-input btn btn-dark btn-lg" type="SUBMIT" >Edit</button>
                    {% else %}
                    <button class="form-input btn btn-dark btn-lg" type="SUBMIT" >Create</button>
                    {% endif %}

                </form>
            </div>
        </div>
    </div>

{% endblock main_content %}

books/templates/books/delete.html
{% extends 'core/main.html' %}

{% block main_content %}
    <style>
        h1 {
        color: white;
        font-weight: bold;
        text-align: center;
        margin: 1rem;
        margin-bottom: 9rem;
        }

        .div-form {
            border-radius: 10px;
            background-color: rgb(100, 98, 105);
        }
    </style>

    <div class="d-flex flex-column justify-content-center align-items-center">
        <div>
        <h1>Delete this book?</h1>
        </div>

        <form  class="div-form d-flex justify-content-around align-items-center" style="height: 20vh; width: 25rem;" action="" method="POST">

                <a href=" {% url 'books:detail' object.pk %}" class="btn btn-dark btn-lg" style="width: 10rem;">Cancel</a>
                <button type="submit" class="btn  btn-danger btn-lg" style="width: 10rem;">Delete</button>
            
            {% csrf_token %}
        </form>
    </div>
{% endblock main_content %}

books/templates/books/detail.html
{% extends 'core/main.html' %}

{% block main_content %}
<style>
    h1 {
      color: white;
      font-weight: bold;
      text-align: center;
      margin: 1rem;
      margin-bottom: 9rem;
    }

</style>

<div>
<h1>Detail Of Book</h1>
</div>

<div class="d-flex justify-content-center">
    <div>
        <div class="card" style="width: 30vw;">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <p class="card-text"> <strong>Summary</strong>: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean ullamcorper dolor eu sem auctor, at hendrerit magna viverra. Phasellus vestibulum mi at pretium interdum. In imperdiet nisi in lacus gravipsum dolor sit amet, consectetur adipiscing elit. Aenean ullamcorper dolor eu sem auctor, at hendrerit magna viverra. Phasellus vestibuluuctor, at hendrerit magna viverra. Phasellus vestibulum mi at pretium intm mi at pretium interdum. In imperdiet nisi in lacus gravidaida.</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>Author(s):</strong> 
                    {% for author in object.author.all  %}
                        {{author.first_name}} {{author.last_name}}.
                    {% endfor %}</li>
                <li class="list-group-item"><strong>Publishign House:</strong> {{book.publishing_house}}</li>
                <li class="list-group-item"><strong>Publishign Year:</strong> {{book.publishing_year|date:"Y"}}</li>
                <li class="list-group-item"><strong>Pages:</strong> {{book.pages}}</li>

            </ul>
            <div class="card-body d-flex justify-content-around">
                {% if perms.books.change_book %}
                <div>
                    <a href= "{% url 'books:update' object.pk %}" class="btn btn-dark btn-lg" style="width: 10vw;">Edit</a>
                </div>
                {% endif %}

                {% if perms.books.delete_book %}
                <div>
                    <a href="{% url 'books:delete' object.pk %}" class="btn btn-danger btn-lg" style="width: 10vw;">Delete</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock main_content %}

books/templates/books/list.html
{% extends 'core/main.html' %}


{% block main_content %}

<style>

    .card-h:hover {
    background-color: white;
    }

    .card-h {
    background-color: rgb(244, 243, 248);
    }

    h1 {
      color: white;
      font-weight: bold;
      text-align: center;
      margin: 1rem;
      margin-bottom: 4rem;
    }

    a {
        text-decoration: none;
    }

    a:link {
  color: black;
  }

  h3 {
    color: white;
    font-weight: bold;
    margin-left: 2vw;
    }   

a:visited {
  color: black;
}
</style>

<h1>List Of Books</h1>
<h3>Libros Registrados: {{count}}</h3>
    <div class="d-flex flex-wrap justify-content-center">
        {% for book in object_list %}
        <div class="card" style="width: 20rem; margin: 1rem;" >
            <div class="card-body card-h">
                <a href="{% url 'books:detail' book.pk %}"> <h5 class="card-title"> {{book.title}} </h5> </a>
                <hr>
                <h6 class="card-subtitle mb-2 text-muted"> 
                        <strong>Author(s):</strong>
                        {% for author in book.author.all  %}
                            {{author.first_name}} {{author.last_name}}.
                        {% endfor %}
                </h6>
            </div>
        </div>  
        {% endfor %}
    </div>

{% endblock main_content%}

core/templates/core/contact-us.html
{% extends 'core/main.html' %}

{% block main_content %}
        <style>
        h1 {
        color: white;
        font-weight: bold;
        text-align: center;
        margin: 1rem;
        margin-bottom: 4rem;
        }

        .div-form {
            border-radius: 10px;
            background-color: rgb(100, 98, 105);
        }

        .form-input {
            margin: 1rem;
        }
        
        .input-label {
            color: white;
            font-weight: bolder;
        }
    </style>

    <div class="d-flex flex-column justify-content-center align-items-center">
        <div>
        <h1>Contact Us</h1>
        </div>

        <div class="div-form">
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger m-2">
                        {{error}}
                    </div>
                {% endfor %}
            {% endfor %}

            <form class="d-flex flex-column justify-content-between" style="width: 22rem;" action="./" method="POST">
                <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.name.label}}</div>{{form.name}}</div>
                <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.email.label}}</div>{{form.email}}</div>
                <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.phone.label}}</div>{{form.phone}}</div>
                <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{form.message.label}}</div>{{form.message}}</div>

                {% csrf_token %}
                <button class="form-input btn btn-dark btn-lg" type="SUBMIT">Submit</button>
            </form>
        </div>
    </div>
{% endblock main_content %}

core/templates/core/index.html
{% extends 'core/main.html' %}

core/templates/core/main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <title>{{page_title}}</title>
  <link rel="shortcut icon"  href="https://img.icons8.com/flat-round/64/000000/bookmark-book.png"  type="image/x-icon">
</head>

<style>
    body {
        background: rgb(49, 46, 59);
    }
</style>


<body>
  <header>
  {% block header_content %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:list' %}">Library</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
          <ul class="navbar-nav">
            <div class="d-flex">
              <div class="d-flex">
                <li class="nav-item">
                  <a class="nav-link {{nav_text_create}}" href="{% url 'books:create' %}">New Book</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link {{nav_text_contact}}" href="{% url 'core:contact' %}">Contact</a>
                </li>
              </div>
          </ul>
          <ul class="navbar-nav">
              <div class="d-flex">
                <li class="nav-item">
                  <a class="nav-link {{nav_text_singup}}" href="{% url 'core:singup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                  {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'core:logout' %}">Logout</a>
                  {% else %}
                    <a class="nav-link {{nav_text_login}}" href="{% url 'core:login' %}">Login</a>
                  {% endif %}
                </li>
              </div>
            </div>    
          </ul>
        </div>
      </div>
    </nav>
  {% endblock header_content %}
  </header>

  <main>
  {% block main_content %}
  {% endblock main_content%}
  </main>

  <footer>
  {% block fotter_content %}
  {% endblock fotter_content %}
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/singup.html
{% extends 'core/main.html' %}
{% block main_content %}
  <style>
  h1 {
  color: white;
  font-weight: bold;
  text-align: center;
  margin: 1rem;
  margin-bottom: 4rem;
  }

  .div-form {
      border-radius: 10px;
      background-color: rgb(100, 98, 105);
  }

  .form-input {
      margin: 1rem;
  }

  .input-label {
      color: white;
      font-weight: bolder;
  }
  </style>

  <div class="d-flex flex-column justify-content-center align-items-center">
    <div>
      <h1>Sign up Form</h1>
    </div>    
        <div class="div-form">
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger m-2">
                        {{error}}
                    </div>
                {% endfor %}
            {% endfor %}

          <form method="post" class="d-flex flex-column justify-content-between" style="width: 22rem;" >
          {% for field in form %}
            <div class="form-input form-label d-flex flex-column justify-content-between"><div class="input-label">{{ field.label_tag }}</div>{{ field }}</div>
          {% endfor %}
          {% csrf_token %}
          <button class="form-input btn btn-dark btn-lg" type="SUBMIT">Submit</button>

          </form>
      </div>
  </div>
{% endblock main_content %}






  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}

      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %}

      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}

    </p>
  {% endfor %}

core/templates/core/thank-you.html
{% extends 'core/main.html' %}

{% block main_content %}
    <style>
        h1 {
        color: white;
        font-weight: bold;
        font-size: 150px;
        text-align: center;
        margin: 1rem;
        margin-top: 12rem;
        }

        h3 {
            color: white;
            font-weight: bold;
            text-align: center;
        }

    </style>
    <h1>Thanks!</h1>
    <h3>Your comments are really appreciated!<br>We will contact you if necessary</h3>
{% endblock main_content %}